### ISSUE TITLE
Falta de ext.informes y ext.organigrama para conseguir arrancar la aplicación

### ISSUE THREAD

**Issue by arkabide** [zaragoza-sedeelectronica/ext.contratacion#1]
Hola,

Estoy intentando montar el proyecto y  hay dos dependencias que no he encontrado: dentro del pom.xml de opencity.ext.contratacion,  son los artefactos ext.organigrama y ext.informes. He buscado en otros proyectos de la entidad, por si podrían estar sus jars ahí, pero no he tenido suerte, ¿sería posible que subierais esas dependencias a este repo?

Muchas gracias de antemano

**Comment by runobe** [comment]
Hola, hemos incorporado en la carpeta librerías los jars tanto de ext.organigrama como ext.informes.
Un saludo

**Comment by arkabide** [comment]
Muchísimas gracias, @runobe, y disculpa de nuevo. ¿Existe una versión del pom.xml actualizado? Entrando más al detalle he visto que faltan dependencias por declarar (por clases presentes en las clases). Concretamente, y pudiendo dejarme alguna:

Propia:
opencity.ext.core.web

Externa:
com.hp.hpl.jena
com.fasterxml.jackson
javax.persistence
javax.validation
javax.ws
javax.xml
org.apache.commons
org.apache.poi
org.apache.solr
org.hibernate
org.slf4j
org.springframework
org.thymeleaf

Las externas creo que las puedo encontrar en el repo central de Maven (la propia no, claro), pero supongo que, además, hay una combinación concreta de versiones para que funcione correctamente el proyecto. Es por esto que me preguntaba si disponéis de un pom.xml actualizado con todas las dependencias incoporadas.

Gracias de antemano.
