### ISSUE TITLE
Falta de dependencias en el pom.xml para conseguir arrancar la aplicación

### ISSUE THREAD

**Issue by arkabide** [zaragoza-sedeelectronica/ext.contratacion#2]
Hola,

¿Existe una versión del pom.xml actualizado? Faltan algunas dependencias por declarar (por clases presentes en las clases). Concretamente, y pudiendo dejarme alguna:

Propia:
opencity.ext.core.web

Externa:
com.hp.hpl.jena
com.fasterxml.jackson
javax.persistence
javax.validation
javax.ws
javax.xml
org.apache.commons
org.apache.poi
org.apache.solr
org.hibernate
org.slf4j
org.springframework
org.thymeleaf

Las externas creo que las puedo encontrar en el repo central de Maven (la propia no, claro), pero supongo que, además, hay una combinación concreta de versiones para que funcione correctamente el proyecto. Es por esto que me preguntaba si disponéis de un pom.xml actualizado con todas las dependencias incoporadas.

Gracias de antemano.

**Comment by virtor** [comment]
Hola, hicimos un commit hace 28 días, https://github.com/zaragoza-sedeelectronica/ext.contratacion/commit/866a3bc79e9d1e4d81405139c366a26ba606a3b5 allí publicamos algunas librerías que efectivamente faltaban, de forma que en sus pom.xml están las dependencias necesarias, ¿Estás utilizando esta última versión?

Saludos!

**Comment by arkabide** [comment]
Hola, perdonad la espera. Efectivamente, hemos estado trabajando con esas nuevas librerías, pero creo que no son las correctas para la versión del proyecto aquí alojado. Es decir, hemos tenido que añadir las dependencias externas que listaba arriba en el pom.xml con una conjunción de versiones a la que hemos llegado tras unas cuantas pruebas. Sin embargo, nos faltan algunos puntos por resolver.

Por ejemplo, faltan algunos métodos de la clase VirtuosoDataManagement en la librería ext.core-0.0.1.jar, subida en el commit que refieres. Hemos compilado esa librería a partir del repositorio que tiene la Organización y se ha resuelto alguna dependencia, pero, por ejemplo, no encontramos la implementación del método queryExternoTbfy. En el siguiente link, se puede ver que este método no está implementado en ningún repo de la Organización, ¿igual lo tenéis en alguna versión no subida?: [queryExternoTbfy](https://github.com/search?q=org%3Azaragoza-sedeelectronica+queryExternoTbfy&type=code)

En cualquier caso, es muy posible que esto no sea lo único que se necesite para completar el despliegue de la aplicación. Me temo que lo que está aquí subido no es una versión operativa, al menos desde fuera de la red corporativa. Quiero decir, si probáis a clonar y lanzar el repo (sin acceso a repositorios Maven locales que puedan existir y desconocemos), os encontraréis con las mismas carencias que estamos experimentando. ¿Es posible resolver esto? Gracias de antemano.

**Comment by panrod0** [comment]
Hola @virtor, ¿nos podríais echar una mano con lo que comenta @arkabide por favor? estamos pendientes para poder avanzar con la instalación de la aplicación. Gracias.

**Comment by virtor** [comment]
Hola, acabamos de subir los repositorios ext.core y ext.contratacion con la últimas modificaciones de código e incluyendo las librerías necesarias, de todas formas, os paso el resultado de ejecutar mvn dependency:tree ejecutado desde contratacion/opencity.ext.contratacion para que podáis ver las librerías que utilizamos y nos digáis qué falta por subir:

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building contratacion 0.0.1
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for commons-logging:commons-logging:jar:1.1.1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ ext.contratacion ---
[INFO] org.opencity:ext.contratacion:jar:0.0.1
[INFO] +- org.opencity:ext.organigrama:jar:0.0.1:compile
[INFO] |  \- org.opencity:ext.virtuoso:jar:0.0.1:compile
[INFO] |     +- virtuoso.jena.driver:virtjdbc:jar:3:compile
[INFO] |     \- virtuoso.jena:virt_jena:jar:3:compile
[INFO] +- org.opencity:ext.core:jar:0.0.1:compile
[INFO] |  +- org.apache.axis:axis:jar:1.4:compile
[INFO] |  +- org.apache.axis:axis-jaxrpc:jar:1.4:compile
[INFO] |  +- commons-discovery:commons-discovery:jar:0.5:compile
[INFO] |  |  \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  +- org.apache.cxf:cxf-rt-rs-extension-search:jar:2.6.14:compile
[INFO] |  |  \- org.apache.cxf:cxf-rt-frontend-jaxrs:jar:2.6.14:compile
[INFO] |  |     +- org.apache.cxf:cxf-api:jar:2.6.14:compile
[INFO] |  |     |  +- org.codehaus.woodstox:woodstox-core-asl:jar:4.2.1:compile
[INFO] |  |     |  |  \- org.codehaus.woodstox:stax2-api:jar:3.1.4:compile
[INFO] |  |     |  +- org.apache.ws.xmlschema:xmlschema-core:jar:2.0.3:compile
[INFO] |  |     |  +- org.apache.geronimo.specs:geronimo-javamail_1.4_spec:jar:1.7.1:compile
[INFO] |  |     |  \- wsdl4j:wsdl4j:jar:1.6.3:compile
[INFO] |  |     +- org.apache.cxf:cxf-rt-core:jar:2.6.14:compile
[INFO] |  |     |  \- com.sun.xml.bind:jaxb-impl:jar:2.1.13:compile
[INFO] |  |     +- javax.ws.rs:jsr311-api:jar:1.1.1:compile
[INFO] |  |     +- org.apache.cxf:cxf-rt-bindings-xml:jar:2.6.14:compile
[INFO] |  |     \- org.apache.cxf:cxf-rt-transports-http:jar:2.6.14:compile
[INFO] |  +- com.itextpdf:itextpdf:jar:5.5.1:compile
[INFO] |  +- org.apache.commons:commons-text:jar:1.9:compile
[INFO] |  +- org.hibernate:hibernate-core:jar:4.3.11.Final:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.1.3.GA:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:1.2.0.Beta1:compile
[INFO] |  |  +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.0.0.Final:compile
[INFO] |  |  +- dom4j:dom4j:jar:1.6.1:compile
[INFO] |  |  +- org.hibernate.common:hibernate-commons-annotations:jar:4.0.5.Final:compile
[INFO] |  |  +- org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar:1.0.0.Final:compile
[INFO] |  |  +- org.javassist:javassist:jar:3.18.1-GA:compile
[INFO] |  |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  |  \- org.jboss:jandex:jar:1.1.0.Final:compile
[INFO] |  +- org.hibernate:hibernate-validator:jar:5.3.1.Final:compile
[INFO] |  |  \- com.fasterxml:classmate:jar:1.3.1:compile
[INFO] |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  +- org.hibernate:hibernate-entitymanager:jar:4.3.11.Final:compile
[INFO] |  +- org.jsoup:jsoup:jar:1.7.2:compile
[INFO] |  +- com.google.apis:google-api-services-analyticsreporting:jar:v4-rev14-1.22.0:compile
[INFO] |  |  \- com.google.api-client:google-api-client:jar:1.22.0:compile
[INFO] |  |     +- com.google.oauth-client:google-oauth-client:jar:1.22.0:compile
[INFO] |  |     |  +- com.google.http-client:google-http-client:jar:1.22.0:compile
[INFO] |  |     |  \- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] |  |     +- com.google.http-client:google-http-client-jackson2:jar:1.22.0:compile
[INFO] |  |     \- com.google.guava:guava-jdk5:jar:17.0:compile
[INFO] |  +- com.github.jsonld-java:jsonld-java:jar:0.12.3:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.7:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient-osgi:jar:4.5.6:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.6:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpmime:jar:4.5.6:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpclient-cache:jar:4.5.6:compile
[INFO] |  |  |  \- org.apache.httpcomponents:fluent-hc:jar:4.5.6:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore-osgi:jar:4.4.10:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.10:compile
[INFO] |  |  |  \- org.apache.httpcomponents:httpcore-nio:jar:4.4.10:compile
[INFO] |  |  \- commons-io:commons-io:jar:2.6:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.9.7:compile
[INFO] |  +- com.oracle.jdbc:ojdbc6:jar:11.2.0.4:compile
[INFO] |  +- org.apache.solr:solr-solrj:jar:3.2.0:compile
[INFO] |  |  +- org.apache.geronimo.specs:geronimo-stax-api_1.0_spec:jar:1.0.1:compile
[INFO] |  |  +- org.apache.zookeeper:zookeeper:jar:3.3.1:compile
[INFO] |  |  |  \- jline:jline:jar:0.9.94:compile
[INFO] |  |  \- org.codehaus.woodstox:wstx-asl:jar:3.2.7:compile
[INFO] |  |     \- stax:stax-api:jar:1.0.1:compile
[INFO] |  +- idezar:geoapi:jar:2.0:compile
[INFO] |  +- idezar:deegree2-pre:jar:2:compile
[INFO] |  +- idezar:geoapi-nogenerics:jar:2.1-M2:compile
[INFO] |  +- idezar:gsl-coordinate-transformation:jar:1.0-jdk15:compile
[INFO] |  +- idezar:gt2-epsg-wkt:jar:2.3.5:compile
[INFO] |  +- idezar:gt2-referencing:jar:2.3.0:compile
[INFO] |  +- idezar:iaaa_csct:jar:1.6.2:compile
[INFO] |  +- idezar:j3dcore:jar:1.3.0:compile
[INFO] |  +- idezar:j3dutils:jar:1.3.0:compile
[INFO] |  +- idezar:jai_codec:jar:1.1.1_01:compile
[INFO] |  +- idezar:jai_core:jar:1.1.1_01:compile
[INFO] |  +- idezar:jGridShiftApi:jar:2.0:compile
[INFO] |  +- idezar:jsr108:jar:0.01:compile
[INFO] |  +- idezar:jts:jar:1.6:compile
[INFO] |  +- idezar:vecmath:jar:1.3.1:compile
[INFO] |  +- com.hp.hpl.jena:tdb:jar:0.8.10:compile
[INFO] |  |  +- com.hp.hpl.jena:arq:jar:2.8.8:compile
[INFO] |  |  |  \- org.apache.lucene:lucene-core:jar:2.3.1:compile
[INFO] |  |  +- com.hp.hpl.jena:jena:jar:2.6.4:compile
[INFO] |  |  |  \- xerces:xercesImpl:jar:2.7.1:compile
[INFO] |  |  \- com.hp.hpl.jena:iri:jar:0.8:compile
[INFO] |  +- com.ibm.icu:icu4j:jar:3.4.4:compile
[INFO] |  +- org.thymeleaf:thymeleaf:jar:3.0.11.RELEASE:compile
[INFO] |  |  +- ognl:ognl:jar:3.1.12:compile
[INFO] |  |  +- org.attoparser:attoparser:jar:2.0.5.RELEASE:compile
[INFO] |  |  \- org.unbescape:unbescape:jar:1.1.6.RELEASE:compile
[INFO] |  +- org.thymeleaf:thymeleaf-spring5:jar:3.0.11.RELEASE:compile
[INFO] |  +- commons-httpclient:commons-httpclient:jar:3.0:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.2:compile
[INFO] |  +- commons-pool:commons-pool:jar:1.4:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] |  +- commons-validator:commons-validator:jar:1.4.0:compile
[INFO] |  |  +- commons-beanutils:commons-beanutils:jar:1.8.3:compile
[INFO] |  |  \- commons-digester:commons-digester:jar:1.8:compile
[INFO] |  +- commons-dbcp:commons-dbcp:jar:1.4:compile
[INFO] |  +- commons-fileupload:commons-fileupload:jar:1.2:compile
[INFO] |  +- com.sun.mail:javax.mail:jar:1.5.2:compile
[INFO] |  |  \- javax.activation:activation:jar:1.1:compile
[INFO] |  +- javax.xml.bind:jaxb-api:jar:2.2.3:compile
[INFO] |  |  \- javax.xml.stream:stax-api:jar:1.0-2:compile
[INFO] |  +- org.springframework:spring-context-support:jar:5.1.3.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-beans:jar:5.1.3.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-core:jar:5.1.3.RELEASE:compile
[INFO] |  |     \- org.springframework:spring-jcl:jar:5.1.3.RELEASE:compile
[INFO] |  +- net.sf.ehcache:ehcache-core:jar:2.4.6:compile
[INFO] |  +- net.sf.ehcache:ehcache-web:jar:2.0.4:compile
[INFO] |  +- org.springframework:spring-context:jar:5.1.3.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-aop:jar:5.1.3.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-expression:jar:5.1.3.RELEASE:compile
[INFO] |  +- org.springframework:spring-webmvc:jar:5.1.3.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-web:jar:5.1.3.RELEASE:compile
[INFO] |  +- org.springframework:spring-orm:jar:5.1.3.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-jdbc:jar:5.1.3.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-tx:jar:5.1.3.RELEASE:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.2:compile
[INFO] |  +- org.slf4j:jcl-over-slf4j:jar:1.7.2:runtime
[INFO] |  +- org.slf4j:slf4j-log4j12:jar:1.7.2:runtime
[INFO] |  +- log4j:log4j:jar:1.2.15:compile
[INFO] |  |  \- javax.mail:mail:jar:1.4:compile
[INFO] |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.8.2:runtime
[INFO] |  |  \- org.apache.logging.log4j:log4j-api:jar:2.8.2:runtime
[INFO] |  +- org.springframework.mobile:spring-mobile-device:jar:1.1.5.RELEASE:compile
[INFO] |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  +- com.notnoop.apns:apns:jar:1.0.0.Beta6:compile
[INFO] |  \- info.debatty:java-string-similarity:jar:2.0.0:compile
[INFO] |     \- net.jcip:jcip-annotations:jar:1.0:compile
[INFO] +- org.opencity:ext.informes:jar:0.0.1:compile
[INFO] |  +- org.apache.poi:poi:jar:4.1.2:compile
[INFO] |  |  +- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO] |  |  +- org.apache.commons:commons-math3:jar:3.6.1:compile
[INFO] |  |  \- com.zaxxer:SparseBitSet:jar:1.2:compile
[INFO] |  +- org.apache.poi:poi-ooxml:jar:4.1.2:compile
[INFO] |  |  +- org.apache.poi:poi-ooxml-schemas:jar:4.1.2:compile
[INFO] |  |  |  \- org.apache.xmlbeans:xmlbeans:jar:3.1.0:compile
[INFO] |  |  +- org.apache.commons:commons-compress:jar:1.19:compile
[INFO] |  |  \- com.github.virtuald:curvesapi:jar:1.06:compile
[INFO] |  +- com.github.miachm.sods:SODS:jar:1.4.0:compile
[INFO] |  +- com.opencsv:opencsv:jar:5.5.2:compile
[INFO] |  \- net.sf.jasperreports:jasperreports:jar:4.1.3:compile
[INFO] |     +- commons-collections:commons-collections:jar:2.1:compile
[INFO] |     +- com.lowagie:itext:jar:2.1.7:compile
[INFO] |     |  +- bouncycastle:bcmail-jdk14:jar:138:compile
[INFO] |     |  +- bouncycastle:bcprov-jdk14:jar:138:compile
[INFO] |     |  \- org.bouncycastle:bctsp-jdk14:jar:1.38:compile
[INFO] |     |     +- org.bouncycastle:bcprov-jdk14:jar:1.38:compile
[INFO] |     |     \- org.bouncycastle:bcmail-jdk14:jar:1.38:compile
[INFO] |     +- jfree:jcommon:jar:1.0.15:compile
[INFO] |     +- jfree:jfreechart:jar:1.0.12:compile
[INFO] |     +- xml-apis:xml-apis:jar:1.3.02:compile
[INFO] |     +- eclipse:jdtcore:jar:3.1.0:compile
[INFO] |     +- org.codehaus.castor:castor:jar:1.2:compile
[INFO] |     +- org.codehaus.jackson:jackson-core-lgpl:jar:1.7.4:compile
[INFO] |     \- org.codehaus.jackson:jackson-mapper-lgpl:jar:1.7.4:compile
[INFO] +- org.opencity:ext.core.test:jar:0.0.1:test
[INFO] |  +- junit:junit:jar:4.12:compile
[INFO] |  |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] |  +- org.mockito:mockito-core:jar:2.21.0:test
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.8.15:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.8.15:test
[INFO] |  |  \- org.objenesis:objenesis:jar:2.6:test
[INFO] |  +- org.springframework:spring-test:jar:5.1.3.RELEASE:test
[INFO] |  +- javax.el:javax.el-api:jar:2.2.4:test
[INFO] |  +- org.glassfish.web:javax.el:jar:2.2.4:test
[INFO] |  \- org.apache.tomcat:tomcat-catalina:jar:7.0.47:test
[INFO] |     +- org.apache.tomcat:tomcat-servlet-api:jar:7.0.47:test
[INFO] |     +- org.apache.tomcat:tomcat-juli:jar:7.0.47:test
[INFO] |     +- org.apache.tomcat:tomcat-annotations-api:jar:7.0.47:test
[INFO] |     +- org.apache.tomcat:tomcat-api:jar:7.0.47:test
[INFO] |     \- org.apache.tomcat:tomcat-util:jar:7.0.47:test
[INFO] \- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.935 s
[INFO] Finished at: 2022-03-08T08:02:19+01:00
[INFO] Final Memory: 21M/413M
[INFO] ------------------------------------------------------------------------

**Comment by arkabide** [comment]
Con el árbol de dependencias y las actualizaciones hemos conseguido compilar este proyecto y generar la librería ext-contratacion.jar. Por tanto, puede cerrarse esta incidencia.

Muchas gracias!
