### ISSUE TITLE
Plugin org.opencity:shared-resources necesario para ejecutar correctamente ext-web

### ISSUE THREAD

**Issue by arkabide** [zaragoza-sedeelectronica/ext.contratacion#3]
Hola,

Tras generar la librería ext-contratacion.jar e incorporarla en ext-web, necesitaríamos tener acceso al plugin org.opencity:shared-resources para poder desplegar la aplicación web y acceder a ella.

Hemos buscado y en varios repos de esta organización se referencia dicho plugin en ficheros pom.xml, pero no hemos podido localizar el código fuente o artefacto. La búsqueda que hemos hecho es esta: https://github.com/search?q=org%3Azaragoza-sedeelectronica+shared-resources&type=code

Comentando las líneas de dicho plugin en el pom.xml, conseguimos compilar el proyecto web, pero no despliega correctamente, por lo que entendemos que es necesario para su funcionamiento.

Muchas gracias de antemano!

**Comment by panrod0** [comment]
Hola @runobe @virtor ¿nos podríais echar una mano con esto? muchas gracias

**Comment by virtor** [comment]
Hemos subido los template para los ficheros de propiedades, la idea de shared-resources es reutilizar los mismos ficheros de propiedades entre difetentes repositorios, pero comentando el plugin debería de ser suficiente, una vez configurado los ficheros application.properties y context.xml según se explica en https://github.com/zaragoza-sedeelectronica/ext.contratacion/#configurar-la-base-de-datos-en-el-proyecto-opencityextweb y en https://github.com/zaragoza-sedeelectronica/ext.contratacion/#configuraci%C3%B3n-del-m%C3%B3dulo
